evidence_binary="strided"
evidence_filename="evidence_file.json"

[chains]
[chains.cosmoshub]
chain_id="cosmoshub-4"
api=""
rpc=""
binary="gaiad"

[chains.neutron]
chain_id="neutron-1"
api=""
rpc=""
binary="neutrond"

[chains.stride]
chain_id="stride-1"
api=""
rpc=""
binary="strided"
